var car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
var car1 = 'toyota';
console.log("Is car == 'toyota'? I predict True.");
console.log(car1 == 'toyota');
var car2 = 'honda';
console.log("Is car == 'subaru'? I predict True.");
console.log(car2 == 'honda');
var car3 = 'hawai';
console.log("Is car == 'subaru'? I predict True.");
console.log(car3 == 'hawai');
var car4 = 'civic';
console.log("Is car == 'subaru'? I predict True.");
console.log(car4 == 'civic');
console.log("Is car == 'subaru'? I predict false.");
console.log(car2 == 'subaru');
console.log("Is car == 'subaru'? I predict false.");
console.log(car3 == 'toyota');
console.log("Is car == 'subaru'? I predict false.");
console.log(car4 == 'hawai');
console.log("Is car == 'subaru'? I predict false.");
console.log(car1 == 'civic');
console.log("Is car == 'subaru'? I predict false.");
console.log(car == 'hawai');
